dist: trusty
sudo: required

services:
  - docker

install:
  - set -e
  - echo "clone parent repo and link this repo as plugin to it"
  - this_repo=$(pwd)
  - mkdir ../farm
  - git clone --depth=1 https://github.com/AndriiNikitin/mariadb-environs ../farm
  - rm -r ../farm/_plugin/docker
  - ln -s $this_repo ../farm/_plugin/docker
  - cd ../farm

env:
  matrix:
    # centos installer doesn't allow upgrades between major versions
    - MATRIX_IMAGE=centos~6 MATRIX_MDB_VERSIONS='5.5.50 5.5' MATRIX_MAXSCALE_VERSIONS='1.4 2.1' MATRIX_INSTALL_XTRABACKUP=1
    - MATRIX_IMAGE=centos~7 MATRIX_MDB_VERSIONS='5.5.50 5.5' MATRIX_MAXSCALE_VERSIONS='1.4 2.0' MATRIX_INSTALL_XTRABACKUP=1
    - MATRIX_IMAGE=centos~6 MATRIX_MDB_VERSIONS='10.0.22 10.0' MATRIX_MAXSCALE_VERSIONS='1.2 2.1' MATRIX_INSTALL_XTRABACKUP=1
    - MATRIX_IMAGE=centos~7 MATRIX_MDB_VERSIONS='10.0.22 10.0' MATRIX_MAXSCALE_VERSIONS='1.4.4 2.1' MATRIX_INSTALL_XTRABACKUP=1
    - MATRIX_IMAGE=centos~6 MATRIX_MDB_VERSIONS='10.1.22 10.1' MATRIX_MAXSCALE_VERSIONS='2.0.5 2.1' MATRIX_INSTALL_XTRABACKUP=1
    - MATRIX_IMAGE=centos~7 MATRIX_MDB_VERSIONS='10.1.22 10.1' MATRIX_MAXSCALE_VERSIONS='2.0 2.1' MATRIX_INSTALL_XTRABACKUP=1
    - MATRIX_IMAGE=centos~6 MATRIX_MDB_VERSIONS='10.2.2 10.2'  MATRIX_MAXSCALE_VERSIONS='2.0.5 2.1' MATRIX_INSTALL_XTRABACKUP=1
    - MATRIX_IMAGE=centos~7 MATRIX_MDB_VERSIONS='10.2.2 10.2'  MATRIX_MAXSCALE_VERSIONS='2.0.2 2.1' MATRIX_INSTALL_XTRABACKUP=1

    - MATRIX_IMAGE=ubuntu~trusty MATRIX_MDB_VERSIONS='5.5.50 5.5 10.0.28 10.0 10.1.20 10.1 10.2' MATRIX_MAXSCALE_VERSIONS='1.2 1.4.4 1.4 2.0 2.1' MATRIX_INSTALL_XTRABACKUP=1
    - MATRIX_IMAGE=ubuntu~xenial MATRIX_MDB_VERSIONS='10.0.25 10.0 10.1.20 10.1 10.2' MATRIX_MAXSCALE_VERSIONS='1.4.3 1.4 2.0.4 2.1' MATRIX_INSTALL_XTRABACKUP=1

    - MATRIX_IMAGE=debian~wheezy MATRIX_MDB_VERSIONS='5.5.49 5.5 10.0.28 10.0 10.1.20 10.1 10.2' MATRIX_MAXSCALE_VERSIONS='1.2 1.4 2.0 2.1' MATRIX_INSTALL_XTRABACKUP=1
    - MATRIX_IMAGE=debian~jessie MATRIX_MDB_VERSIONS='10.0.22 10.0 10.1.20 10.1 10.2.4 10.2' MATRIX_MAXSCALE_VERSIONS='1.4 2.0 2.1' MATRIX_INSTALL_XTRABACKUP=1


script:
  - _plugin/docker/_testscript/mariadb_repo_setup.sh $MATRIX_INSTALL_XTRABACKUP "$MATRIX_MAXSCALE_VERSIONS" "$MATRIX_MDB_VERSIONS" $MATRIX_IMAGE 0

